var Keyboard = {
  keycode: keycode,
  hotkeys: {
    register: function(hotkey) {
      Keyboard.hotkeys[hotkey.keyCode] = hotkey;
    }
  },
  layout: {
    name: 'qwerty',
    keyrows: [
      ["`","1","2","3","4","5","6","7","8","9","0","-","="],
      ["q","w","e","r","t","y","u","i","o","p","[","]"],
      ["a","s","d","f","g","h","j","k","l",";","'"],
      ["z","x","c","v","b","n","m",",",".","/"]
    ]
  },
  state: {
    "backspace": { keyCode: 8 },
    "tab": { keyCode: 9 },
    "enter": { keyCode: 13 },
    "shift": { keyCode: 16 },
    "ctrl": { keyCode: 17 },
    "alt": { keyCode: 18 },
    "pause": { keyCode: 19 },
    "capslock": { keyCode: 20 },
    "escape": { keyCode: 27 },
    "pgup": { keyCode: 33 },
    "pgdown": { keyCode: 34 },
    "end": { keyCode: 35 },
    "home": { keyCode: 36 },
    "left": { keyCode: 37 },
    "up": { keyCode: 38 },
    "right": { keyCode: 39 },
    "down": { keyCode: 40 },
    "insert": { keyCode: 45 },
    "delete": { keyCode: 46 },
    "0": { keyCode: 48 },
    "1": { keyCode: 49 },
    "2": { keyCode: 50 },
    "3": { keyCode: 51 },
    "4": { keyCode: 52 },
    "5": { keyCode: 53 },
    "6": { keyCode: 54 },
    "7": { keyCode: 55 },
    "8": { keyCode: 56 },
    "9": { keyCode: 57 },
    "a": { keyCode: 65 },
    "b": { keyCode: 66 },
    "c": { keyCode: 67 },
    "d": { keyCode: 68 },
    "e": { keyCode: 69 },
    "f": { keyCode: 70 },
    "g": { keyCode: 71 },
    "h": { keyCode: 72 },
    "i": { keyCode: 73 },
    "j": { keyCode: 74 },
    "k": { keyCode: 75 },
    "l": { keyCode: 76 },
    "m": { keyCode: 77 },
    "n": { keyCode: 78 },
    "o": { keyCode: 79 },
    "p": { keyCode: 80 },
    "q": { keyCode: 81 },
    "r": { keyCode: 82 },
    "s": { keyCode: 83 },
    "t": { keyCode: 84 },
    "u": { keyCode: 85 },
    "v": { keyCode: 86 },
    "w": { keyCode: 87 },
    "x": { keyCode: 88 },
    "y": { keyCode: 89 },
    "z": { keyCode: 90 },
    ";": { keyCode: 186 },
    "=": { keyCode: 187 },
    ",": { keyCode: 188 },
    "-": { keyCode: 189 },
    ".": { keyCode: 190 },
    "/": { keyCode: 191 },
    "`": { keyCode: 192 },
    "[": { keyCode: 219 },
    "\\": { keyCode: 220 },
    "]": { keyCode: 221 },
    "'": { keyCode: 222 },
    "numpad0": { keyCode: 96 },
    "numpad1": { keyCode: 97 },
    "numpad2": { keyCode: 98 },
    "numpad3": { keyCode: 99 },
    "numpad4": { keyCode: 100 },
    "numpad5": { keyCode: 101 },
    "numpad6": { keyCode: 102 }
  }
}

function keycode(keychord) {
  // TODO: fill this out with "^z" sort of codes like AHK.
  return Keyboard.state[keychord].keyCode;
}
